# Generated by Django 3.0.3 on 2020-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
