# Generated by Django 3.0.3 on 2020-03-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='countryname',
            new_name='countryName',
        ),
    ]
