# Generated by Django 3.0.3 on 2020-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0002_auto_20200513_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='lat',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towns',
            name='lng',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
