# Generated by Django 3.0.3 on 2020-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0002_auto_20200322_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='pwd_test',
            field=models.CharField(default='testpwd', max_length=50),
            preserve_default=False,
        ),
    ]
