# Generated by Django 3.0.3 on 2020-05-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0003_auto_20200523_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
