# Generated by Django 3.0.3 on 2020-03-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0003_persons_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolImages',
            fields=[
                ('id_toolImage', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tools')),
            ],
            options={
                'db_table': 'ToolImages',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='tools',
            name='toolimages',
        ),
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.EmailField(blank=True, default='a@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ToolsToolImages',
            fields=[
                ('id_tool', models.OneToOneField(db_column='id_tool', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='toolbox_app.Tools')),
                ('id_toolImage', models.ForeignKey(db_column='id_toolImage', on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox_app.ToolImages')),
            ],
            options={
                'db_table': 'ToolsToolImages',
                'managed': True,
                'unique_together': {('id_tool', 'id_toolImage')},
            },
        ),
    ]
