# Generated by Django 3.0.3 on 2020-03-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0003_auto_20200311_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='toolname',
            field=models.CharField(default='no Name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='persons',
            constraint=models.UniqueConstraint(fields=('alias',), name='unique_alias'),
        ),
    ]
