# Generated by Django 3.0.3 on 2020-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0004_auto_20200413_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolimages',
            name='image',
            field=models.ImageField(upload_to='../DB/data/toolsImgs'),
        ),
    ]
