# Generated by Django 3.0.3 on 2020-03-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0004_auto_20200314_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toolstoolimages',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='toolstoolimages',
            name='id_tool',
        ),
        migrations.RemoveField(
            model_name='toolstoolimages',
            name='id_toolImage',
        ),
        migrations.DeleteModel(
            name='ToolImages',
        ),
        migrations.DeleteModel(
            name='ToolsToolImages',
        ),
    ]
