# Generated by Django 3.0.3 on 2020-03-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0005_auto_20200315_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolImages',
            fields=[
                ('id_toolImage', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tools')),
                ('id_tool', models.ForeignKey(db_column='id_tool', on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox_app.Tools')),
            ],
            options={
                'db_table': 'ToolImages',
                'managed': True,
            },
        ),
    ]
