# Generated by Django 3.0.3 on 2020-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0005_auto_20200413_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolimages',
            name='image',
            field=models.ImageField(upload_to='toolsImgs'),
        ),
    ]
