# Generated by Django 3.0.3 on 2020-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0006_auto_20200413_1546'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='persons',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
