# Generated by Django 3.0.3 on 2020-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0007_auto_20200422_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='pwd_test',
        ),
        migrations.AddField(
            model_name='persons',
            name='password',
            field=models.CharField(default='testPwd1', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persons',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persons',
            name='lastName',
            field=models.CharField(max_length=150),
        ),
    ]
