# Generated by Django 3.0.3 on 2020-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0008_auto_20200423_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='groupDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
