# Generated by Django 3.0.3 on 2020-03-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_countrycode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('countryname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_groupname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('grouptype', models.CharField(blank=True, max_length=7, null=True)),
                ('grouprange', models.IntegerField()),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupsmembers',
            fields=[
                ('id_person', models.OneToOneField(db_column='id_person', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='toolbox_app.Persons')),
                ('groupadmin', models.BooleanField()),
            ],
            options={
                'db_table': 'groupsmembers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personreviews',
            fields=[
                ('id_personreview', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personreviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personstowns',
            fields=[
                ('id_personstowns', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'personstowns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Toolreviews',
            fields=[
                ('id_toolreview', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toolreviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id_tool', models.AutoField(primary_key=True, serialize=False)),
                ('toolname', models.CharField(blank=True, max_length=30, null=True)),
                ('tooldescription', models.TextField(blank=True, null=True)),
                ('toolprice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('toolimages', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id_town', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.IntegerField()),
                ('townname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'towns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Toolsgroups',
            fields=[
                ('id_tool', models.OneToOneField(db_column='id_tool', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='toolbox_app.Tools')),
            ],
            options={
                'db_table': 'toolsgroups',
                'managed': False,
            },
        ),
    ]
