# Generated by Django 3.0.3 on 2020-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=30)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
    ]
